### ISSUE TITLE
plt.pause(0.001) keeps bringing plot window to forefront

### ISSUE THREAD

**Issue by NicolasMICAUX** [embaba/swarm-rescue#3]
It get the same issue as described [here](https://stackoverflow.com/questions/45729092/make-interactive-matplotlib-window-not-pop-to-front-on-each-update-windows-7) when running `drone_abstract.py` because of the way `plt.pause(0.001)` works : window keeps coming to forefront, so I cannot move the drone with keyboard.

Changing backend ('QtAgg', 'tkAgg', ...) does not help.

Ubuntu 20.04
python3.8.10
pyQt5, Qt5 (latest pip versions)
opencv==4.2.0.34 (could not update to 4.5 because of [a bug with xcb](https://forum.qt.io/topic/119109/using-pyqt5-with-opencv-python-cv2-causes-error-could-not-load-qt-platform-plugin-xcb-even-though-it-was-found))

**Comment by filliat** [comment]
I had the same problem on macOS. Remplacing plt.pause(0.001) by plt.show() worked for me. Can you try ?

**Comment by NicolasMICAUX** [comment]
plt.show() does not work on Ubuntu

ok I re-tested with backend tkagg, in fact it does work

thx for your help !
