### ISSUE TITLE
Missing number_drones in MiscData in Launcher.reset()

### ISSUE THREAD

**Issue by AlbeBertin** [embaba/swarm-rescue#6]
Swarm is built in init() and in reset() (could be deleted from init as it is built before every round).

In Launcher.reset() [L73](https://github.com/embaba/swarm-rescue/blob/main/src/swarm_rescue/launcher.py#L73), the correct code is `misc_data = MiscData(size_area=self.my_map.size_area, number_drones=self.my_map.number_drones)`.

**Comment by embaba** [comment]
Thank you. It is corrected, in version 1.4.1
