### ISSUE TITLE
pathlib or pathlib2 in requirements.txt

### ISSUE THREAD

**Issue by NicolasMICAUX** [embaba/swarm-rescue#7]
Hi
requirements.txt contains `pathlib` which seems to be ab abandonned package (https://pypi.org/project/pathlib/)
Erwan has trouble installing it
Can we switch to `pathlib2` please ? (https://pypi.org/project/pathlib2/)

**Comment by embaba** [comment]
Hi,
Ok. Switching from pathlib to pathlib2 doesn't seem to be a problem.

On which OS do you have some troubles to install pathlib ?

**Comment by embaba** [comment]
Issue fixed in the version v1.5.0

**Comment by NicolasMICAUX** [comment]
> Hi, Ok. Switching from pathlib to pathlib2 doesn't seem to be a problem.
> 
> On which OS do you have some troubles to install pathlib ?

Erwan is on windows, having trouble installing it. On ubuntu, no pb.
